using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace InspireData
{
    /// <summary>
    /// Class containing all of the Image data
    /// </summary>
    public class ImageData
    {
        // Generated by Xamasoft JSON Class Generator and then stripped out unneeded properties.
        // http://www.xamasoft.com/json-class-generator

        [JsonProperty("url")]
        public string Url { get; set; }
    }
}
