using Newtonsoft.Json;

namespace InspireData
{
    /// <summary>
    /// Class containing all of the Image data
    /// </summary>
    public class ImageData : IImageData
    {
        // Generated by Xamasoft JSON Class Generator and then stripped out unneeded properties.
        // http://www.xamasoft.com/json-class-generator

        /// <summary>
        /// The Url to an image file.
        /// </summary>
        [JsonProperty("url")]
        public string Url { get; set; }
    }
}
