using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace InspireData
{
    /// <summary>
    /// Class containing all of the Quote data
    /// </summary>
    public class QuoteData
    {
        [JsonIgnore]
        public string Author
        {
            get => Title.Rendered;
        }

        [JsonIgnore]
        public string Quote
        {
            get => Content.Rendered;
        }



        // Generated by Xamasoft JSON Class Generator and then stripped out unneeded properties.
        // http://www.xamasoft.com/json-class-generator

        internal class InnerTitle
        {

            [JsonProperty("rendered")]
            public string Rendered { get; set; }
        }

        internal class InnerContent
        {

            [JsonProperty("rendered")]
            public string Rendered { get; set; }
        }

        [JsonProperty("title")]
        internal InnerTitle Title { get; set; }

        [JsonProperty("content")]
        internal InnerContent Content { get; set; }
    }
}
