using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace InspireData
{
    /// <summary>
    /// Class containing all of the Weather data
    /// </summary>
    public class WeatherData
    {

        [JsonIgnore]
        public double CurrentTemperature 
        {
            get => Main.Temp;
        }
        
        [JsonIgnore]
        public double HighTemperature
        {
            get => Main.TempMax;
        }

        [JsonIgnore]
        public double LowTemperature
        {
            get => Main.TempMin;
        }

        [JsonIgnore]
        public string WeatherIcon
        {
            get => Weather[0].Icon;
        }

        [JsonIgnore]
        public string Description
        {
            get => Weather[0].Description;
        }

        // Generated by Xamasoft JSON Class Generator and then stripped out unneeded properties.
        // http://www.xamasoft.com/json-class-generator
        internal class InnerWeather
        {   
            [JsonProperty("main")]
            public string Main { get; set; }

            [JsonProperty("description")]
            public string Description { get; set; }

            [JsonProperty("icon")]
            public string Icon { get; set; }
        }

        internal class InnerMain
        {

            [JsonProperty("temp")]
            public double Temp { get; set; }

            [JsonProperty("temp_min")]
            public double TempMin { get; set; }

            [JsonProperty("temp_max")]
            public double TempMax { get; set; }
        }


        [JsonProperty("weather")]
        internal IList<InnerWeather> Weather { get; set; }

        [JsonProperty("main")]
        internal InnerMain Main { get; set; }
    }
}


